name: Build T^ Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - "TAppAndroid.zip"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip Android project
        run: |
          unzip TAppAndroid.zip -d TAppAndroid

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Grant Gradle permission
        run: |
          chmod +x TAppAndroid/gradlew

      - name: Build APK
        run: |
          cd TAppAndroid
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TApp-debug-apk
          path: TAppAndroid/app/build/outputs/apk/debug/*.apk
